// CRUD with mongo db

const expres = require("express");
const connectDB = require("./db");
const mongo = require("mongodb");

const app = expres();

// *GET*
// we cannot pass the body to GET opreation
// we cannot get the data via '_id'
app.get("/", async (req, resp) => {
  let data = await connectDB();
  data = await data.find().toArray();
  resp.send(data);
  // console.log(data);
  console.log("Data printed on screen coming from DB");
});


// *POST*
// same data can be added multiple times with POST
app.use(expres.json());
app.post("/", async (req, resp) => {
  const db = await connectDB();
  const result = await db.insertMany(req.body);
  console.log(result);
  resp.send(result);
});

// *UPDATE*
// ##(static way)
app.put("/", async (req, resp) => {
  const db = await connectDB();
  const resultt = await db.updateMany({ userId: 1 }, { $set: req.body });
  console.log(req.body);
  resp.send({ STATUS: "updated" });
});

// ##(dynamic way) some isuue with it - not working ## 

// app.put("/:id", async (req, resp) => {
//   console.log(req.params.id);
//   const db = await connectDB();
//   const resultt = await db.updateMany(
//     { "userId": req.params.id},
//     { $set: req.body }
//   );
//   resp.send(req.params.ids);
// });


// *DELETE*
// (static way)
// app.delete("/", async (req, resp) => {
//   const db = await connectDB();
// const res=await db.deleteMany({"userId":3})
//   resp.send(res);
// });

// ##(dynamic way) some isuue with it - not working ## 

// app.delete("/:id", async (req, resp) => {
//   console.log(req.params.id);
//   const db = await connectDB();
// const res=await db.deleteMany({"userId":req.params.id})
//   resp.send(res);
// });

// delete by '_id' generated by mongo itself
app.delete("/:id", async (req, resp) => {
  console.log(req.params.id);
  const db = await connectDB();
  const res = await db.deleteOne({ _id: new mongo.ObjectId(req.params.id) });
  resp.send(res);
});

app.listen("2000",()=>{
  console.log("Server started on http://localhost:2000");
});
